"""
User ORM model.

Maps to the `users` table in PostgreSQL.
All columns use SQLAlchemy 2.0 mapped-column style for full type-safety.

NOTE: This file lives at app/db/models/user.py and is completely separate
from app/models/ which contains the trained ML artefacts.
"""

import uuid
from datetime import date, datetime
from typing import Optional

from sqlalchemy import Date, DateTime, String, Text, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class User(Base):
    """SQLAlchemy ORM model for the `users` table."""

    __tablename__ = "users"

    # ------------------------------------------------------------------ #
    # Primary key — UUID generated server-side by PostgreSQL
    # ------------------------------------------------------------------ #
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        index=True,
        comment="Unique user identifier (UUID v4, generated by PostgreSQL).",
    )

    # ------------------------------------------------------------------ #
    # Name fields
    # ------------------------------------------------------------------ #
    first_name: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        comment="User's first name.",
    )
    middle_name: Mapped[Optional[str]] = mapped_column(
        String(100),
        nullable=True,
        comment="User's middle name (optional).",
    )
    last_name: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        comment="User's last name.",
    )

    # ------------------------------------------------------------------ #
    # Identity fields (unique)
    # ------------------------------------------------------------------ #
    username: Mapped[str] = mapped_column(
        String(50),
        unique=True,
        nullable=False,
        index=True,
        comment="Unique, lowercase alphanumeric username.",
    )
    email: Mapped[str] = mapped_column(
        String(255),
        unique=True,
        nullable=False,
        index=True,
        comment="User's email address — used for login.",
    )

    # ------------------------------------------------------------------ #
    # Security
    # ------------------------------------------------------------------ #
    password_hash: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="bcrypt hash of the user's password. Never store plaintext.",
    )

    # ------------------------------------------------------------------ #
    # Profile fields (all optional — collected progressively)
    # ------------------------------------------------------------------ #
    date_of_birth: Mapped[Optional[date]] = mapped_column(
        Date,
        nullable=True,
        comment="Date of birth — used for age-based health recommendations.",
    )
    health_issue: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        comment="Free-text health condition(s) that affect AQI sensitivity.",
    )
    place_to_visit: Mapped[Optional[str]] = mapped_column(
        String(255),
        nullable=True,
        comment="Destination for route planning and exposure estimation.",
    )

    # ------------------------------------------------------------------ #
    # Timestamps
    # ------------------------------------------------------------------ #
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        comment="Row creation timestamp (set by PostgreSQL).",
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
        comment="Last modification timestamp (updated by SQLAlchemy on every ORM update).",
    )

    # ------------------------------------------------------------------ #
    # Repr
    # ------------------------------------------------------------------ #
    def __repr__(self) -> str:  # pragma: no cover
        return f"<User id={self.id} username={self.username!r} email={self.email!r}>"
