"""Add AdminInvitation and SuperAdmin

Revision ID: 155178ff6f1b
Revises: a6981d8c6aa5
Create Date: 2026-08-17 20:22:59.802286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '155178ff6f1b'
down_revision: Union[str, None] = 'a6981d8c6aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', name='invitationstatus'), nullable=False),
    sa.Column('invited_by_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_invitations_email'), 'admin_invitations', ['email'], unique=True)
    op.create_index(op.f('ix_admin_invitations_id'), 'admin_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_admin_invitations_token'), 'admin_invitations', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_aqi_snapshots',
    sa.Column('city_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('avg_aqi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('max_aqi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('dominant_pollutant', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('active_stations_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city_master.id'], name='city_aqi_snapshots_city_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='city_aqi_snapshots_pkey')
    )
    op.create_index('ix_city_aqi_snapshots_id', 'city_aqi_snapshots', ['id'], unique=False)
    op.create_index('ix_city_aqi_snapshots_city_id', 'city_aqi_snapshots', ['city_id'], unique=False)
    op.create_table('city_master',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('center_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('center_lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('bounding_box', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('waqi_station_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_supported', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='city_master_pkey')
    )
    op.create_index('ix_city_master_name', 'city_master', ['name'], unique=False)
    op.create_index('ix_city_master_id', 'city_master', ['id'], unique=False)
    op.drop_index(op.f('ix_admin_invitations_token'), table_name='admin_invitations')
    op.drop_index(op.f('ix_admin_invitations_id'), table_name='admin_invitations')
    op.drop_index(op.f('ix_admin_invitations_email'), table_name='admin_invitations')
    op.drop_table('admin_invitations')
    # ### end Alembic commands ###
