"""create_users_table

Revision ID: 001_create_users_table
Revises:
Create Date: 2026-07-19 18:47:00 UTC

Creates the `users` table with:
  - UUID primary key (gen_random_uuid())
  - name fields (first, middle, last)
  - unique identity columns (username, email)
  - bcrypt password_hash
  - optional profile fields (date_of_birth, health_issue, place_to_visit)
  - server-managed timestamps (created_at, updated_at)
  - B-tree indexes on id, username, email
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "001_create_users_table"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "users",
        # ── Primary key ──────────────────────────────────────────────
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
            comment="Unique user identifier (UUID v4, generated by PostgreSQL).",
        ),
        # ── Name fields ──────────────────────────────────────────────
        sa.Column(
            "first_name",
            sa.String(length=100),
            nullable=False,
            comment="User's first name.",
        ),
        sa.Column(
            "middle_name",
            sa.String(length=100),
            nullable=True,
            comment="User's middle name (optional).",
        ),
        sa.Column(
            "last_name",
            sa.String(length=100),
            nullable=False,
            comment="User's last name.",
        ),
        # ── Identity fields ──────────────────────────────────────────
        sa.Column(
            "username",
            sa.String(length=50),
            nullable=False,
            unique=True,
            comment="Unique, lowercase alphanumeric username.",
        ),
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=False,
            unique=True,
            comment="User's email address — used for login.",
        ),
        # ── Security ─────────────────────────────────────────────────
        sa.Column(
            "password_hash",
            sa.Text(),
            nullable=False,
            comment="bcrypt hash of the user's password. Never store plaintext.",
        ),
        # ── Optional profile fields ───────────────────────────────────
        sa.Column(
            "date_of_birth",
            sa.Date(),
            nullable=True,
            comment="Date of birth — used for age-based health recommendations.",
        ),
        sa.Column(
            "health_issue",
            sa.Text(),
            nullable=True,
            comment="Free-text health condition(s) that affect AQI sensitivity.",
        ),
        sa.Column(
            "place_to_visit",
            sa.String(length=255),
            nullable=True,
            comment="Destination for route planning and exposure estimation.",
        ),
        # ── Timestamps ───────────────────────────────────────────────
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
            comment="Row creation timestamp (set by PostgreSQL).",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
            comment="Last modification timestamp.",
        ),
    )

    # ── Explicit indexes (id is already indexed as PK) ───────────────
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)


def downgrade() -> None:
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
