"""Add region to user

Revision ID: 652ee45fcbb3
Revises: 155178ff6f1b
Create Date: 2026-08-17 20:38:35.888230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '652ee45fcbb3'
down_revision: Union[str, None] = '155178ff6f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_city_aqi_snapshots_city_id', table_name='city_aqi_snapshots')
    op.drop_index('ix_city_aqi_snapshots_id', table_name='city_aqi_snapshots')
    op.drop_table('city_aqi_snapshots')
    op.drop_index('ix_city_master_id', table_name='city_master')
    op.drop_index('ix_city_master_name', table_name='city_master')
    op.drop_table('city_master')
    op.add_column('prediction_history', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('route_history', sa.Column('start_address', sa.String(length=255), nullable=True))
    op.add_column('route_history', sa.Column('end_address', sa.String(length=255), nullable=True))
    op.add_column('route_waypoints', sa.Column('predicted_aqi', sa.Float(), nullable=True))
    op.add_column('route_waypoints', sa.Column('aqi_category', sa.String(length=50), nullable=True))
    op.add_column('route_waypoints', sa.Column('city_name', sa.String(length=100), nullable=True))
    op.add_column('route_waypoints', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('route_waypoints', sa.Column('pm25', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('region', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'region')
    op.drop_column('route_waypoints', 'pm25')
    op.drop_column('route_waypoints', 'temperature')
    op.drop_column('route_waypoints', 'city_name')
    op.drop_column('route_waypoints', 'aqi_category')
    op.drop_column('route_waypoints', 'predicted_aqi')
    op.drop_column('route_history', 'end_address')
    op.drop_column('route_history', 'start_address')
    op.drop_column('prediction_history', 'city')
    op.create_table('city_master',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('center_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('center_lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('bounding_box', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('waqi_station_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_supported', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='city_master_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_city_master_name', 'city_master', ['name'], unique=False)
    op.create_index('ix_city_master_id', 'city_master', ['id'], unique=False)
    op.create_table('city_aqi_snapshots',
    sa.Column('city_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('avg_aqi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('max_aqi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('dominant_pollutant', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('active_stations_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city_master.id'], name='city_aqi_snapshots_city_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='city_aqi_snapshots_pkey')
    )
    op.create_index('ix_city_aqi_snapshots_id', 'city_aqi_snapshots', ['id'], unique=False)
    op.create_index('ix_city_aqi_snapshots_city_id', 'city_aqi_snapshots', ['city_id'], unique=False)
    # ### end Alembic commands ###
