"""Add user_id to PredictionHistory

Revision ID: 7c5a4a9d6c8a
Revises: 8e6f7513e0aa
Create Date: 2026-08-06 19:32:42.335795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c5a4a9d6c8a'
down_revision: Union[str, None] = '8e6f7513e0aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_advisory_templates',
    sa.Column('aqi_category', sa.String(length=50), nullable=False),
    sa.Column('min_aqi', sa.Float(), nullable=False),
    sa.Column('max_aqi', sa.Float(), nullable=False),
    sa.Column('general_advice', sa.String(length=1024), nullable=False),
    sa.Column('sensitive_group_advice', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_advisory_templates_aqi_category'), 'health_advisory_templates', ['aqi_category'], unique=True)
    op.create_index(op.f('ix_health_advisory_templates_id'), 'health_advisory_templates', ['id'], unique=False)
    op.add_column('prediction_history', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_prediction_history_user_id'), 'prediction_history', ['user_id'], unique=False)
    op.create_foreign_key(None, 'prediction_history', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prediction_history', type_='foreignkey')
    op.drop_index(op.f('ix_prediction_history_user_id'), table_name='prediction_history')
    op.drop_column('prediction_history', 'user_id')
    op.drop_index(op.f('ix_health_advisory_templates_id'), table_name='health_advisory_templates')
    op.drop_index(op.f('ix_health_advisory_templates_aqi_category'), table_name='health_advisory_templates')
    op.drop_table('health_advisory_templates')
    # ### end Alembic commands ###
