"""Add translation table

Revision ID: 8e6f7513e0aa
Revises: f56db674ad7c
Create Date: 2026-07-30 15:57:25.850969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e6f7513e0aa'
down_revision: Union[str, None] = 'f56db674ad7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translations_hash'), 'translations', ['hash'], unique=True)
    op.create_index(op.f('ix_translations_language'), 'translations', ['language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translations_language'), table_name='translations')
    op.drop_index(op.f('ix_translations_hash'), table_name='translations')
    op.drop_table('translations')
    # ### end Alembic commands ###
