"""Initial migration

Revision ID: d1597969bde6
Revises: 
Create Date: 2026-07-22 00:52:05.160539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1597969bde6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_logs',
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=False),
    sa.Column('client_ip', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILURE', 'DEGRADED', name='apistatus'), nullable=False),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_logs_endpoint'), 'api_logs', ['endpoint'], unique=False)
    op.create_index(op.f('ix_api_logs_id'), 'api_logs', ['id'], unique=False)
    op.create_index(op.f('ix_api_logs_status'), 'api_logs', ['status'], unique=False)
    op.create_table('city_master',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('center_lng', sa.Float(), nullable=False),
    sa.Column('bounding_box', sa.String(length=255), nullable=True),
    sa.Column('waqi_station_id', sa.String(length=100), nullable=True),
    sa.Column('is_supported', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_master_id'), 'city_master', ['id'], unique=False)
    op.create_index(op.f('ix_city_master_name'), 'city_master', ['name'], unique=False)
    op.create_table('prediction_history',
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('aqi_value', sa.Float(), nullable=False),
    sa.Column('aqi_category', sa.Enum('GOOD', 'FAIR', 'MODERATE', 'POOR', 'VERY_POOR', 'SEVERE', name='aqicategory'), nullable=False),
    sa.Column('pm25', sa.Float(), nullable=False),
    sa.Column('pm10', sa.Float(), nullable=False),
    sa.Column('no2', sa.Float(), nullable=False),
    sa.Column('so2', sa.Float(), nullable=False),
    sa.Column('o3', sa.Float(), nullable=False),
    sa.Column('co', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=False),
    sa.Column('pressure', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('ensemble_version', sa.String(length=50), nullable=True),
    sa.Column('prediction_latency_ms', sa.Float(), nullable=True),
    sa.Column('prediction_source', sa.Enum('WAQI', 'OPENWEATHER', 'ENSEMBLE_ML', name='predictionsource'), nullable=False),
    sa.Column('prediction_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_history_id'), 'prediction_history', ['id'], unique=False)
    op.create_index(op.f('ix_prediction_history_latitude'), 'prediction_history', ['latitude'], unique=False)
    op.create_index(op.f('ix_prediction_history_longitude'), 'prediction_history', ['longitude'], unique=False)
    op.create_index(op.f('ix_prediction_history_prediction_timestamp'), 'prediction_history', ['prediction_timestamp'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('city_aqi_snapshots',
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('avg_aqi', sa.Float(), nullable=False),
    sa.Column('max_aqi', sa.Float(), nullable=False),
    sa.Column('dominant_pollutant', sa.String(length=50), nullable=False),
    sa.Column('active_stations_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_aqi_snapshots_city_id'), 'city_aqi_snapshots', ['city_id'], unique=False)
    op.create_index(op.f('ix_city_aqi_snapshots_id'), 'city_aqi_snapshots', ['id'], unique=False)
    op.create_table('exposure_history',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('daily_avg_aqi', sa.Float(), nullable=False),
    sa.Column('peak_aqi', sa.Float(), nullable=False),
    sa.Column('total_duration_outdoors_min', sa.Float(), nullable=False),
    sa.Column('cumulative_pm25', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exposure_history_id'), 'exposure_history', ['id'], unique=False)
    op.create_index(op.f('ix_exposure_history_user_id'), 'exposure_history', ['user_id'], unique=False)
    op.create_table('favorite_routes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_lat', sa.Float(), nullable=False),
    sa.Column('start_lng', sa.Float(), nullable=False),
    sa.Column('start_address', sa.String(length=255), nullable=True),
    sa.Column('end_lat', sa.Float(), nullable=False),
    sa.Column('end_lng', sa.Float(), nullable=False),
    sa.Column('end_address', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorite_routes_id'), 'favorite_routes', ['id'], unique=False)
    op.create_index(op.f('ix_favorite_routes_user_id'), 'favorite_routes', ['user_id'], unique=False)
    op.create_table('health_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('primary_condition', sa.Enum('NONE', 'ASTHMA', 'COPD', 'HEART_DISEASE', 'ELDERLY', 'CHILDREN', 'PREGNANT', name='healthcondition'), nullable=False),
    sa.Column('has_asthma', sa.Boolean(), nullable=False),
    sa.Column('has_copd', sa.Boolean(), nullable=False),
    sa.Column('has_heart_disease', sa.Boolean(), nullable=False),
    sa.Column('is_elderly', sa.Boolean(), nullable=False),
    sa.Column('is_pregnant', sa.Boolean(), nullable=False),
    sa.Column('is_child', sa.Boolean(), nullable=False),
    sa.Column('notif_email', sa.Boolean(), nullable=False),
    sa.Column('notif_push', sa.Boolean(), nullable=False),
    sa.Column('notif_sms', sa.Boolean(), nullable=False),
    sa.Column('notif_daily_summary', sa.Boolean(), nullable=False),
    sa.Column('notif_health_alerts', sa.Boolean(), nullable=False),
    sa.Column('notif_route_recommendations', sa.Boolean(), nullable=False),
    sa.Column('notif_weekly_summary', sa.Boolean(), nullable=False),
    sa.Column('notif_emergency_only', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_health_profiles_id'), 'health_profiles', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('notification_type', sa.Enum('HEALTH_ALERT', 'ROUTE_RECOMMENDATION', 'SYSTEM_ALERT', 'DAILY_SUMMARY', 'WEEKLY_SUMMARY', 'EMERGENCY', name='notificationtype'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('route_history',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('start_lat', sa.Float(), nullable=False),
    sa.Column('start_lng', sa.Float(), nullable=False),
    sa.Column('end_lat', sa.Float(), nullable=False),
    sa.Column('end_lng', sa.Float(), nullable=False),
    sa.Column('total_distance_km', sa.Float(), nullable=False),
    sa.Column('estimated_duration_min', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='routestatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_history_id'), 'route_history', ['id'], unique=False)
    op.create_index(op.f('ix_route_history_user_id'), 'route_history', ['user_id'], unique=False)
    op.create_table('health_advisory_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=True),
    sa.Column('route_id', sa.UUID(), nullable=True),
    sa.Column('advisory_text', sa.String(length=1024), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['prediction_history.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['route_history.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_advisory_logs_id'), 'health_advisory_logs', ['id'], unique=False)
    op.create_index(op.f('ix_health_advisory_logs_prediction_id'), 'health_advisory_logs', ['prediction_id'], unique=False)
    op.create_index(op.f('ix_health_advisory_logs_route_id'), 'health_advisory_logs', ['route_id'], unique=False)
    op.create_index(op.f('ix_health_advisory_logs_user_id'), 'health_advisory_logs', ['user_id'], unique=False)
    op.create_table('route_scores',
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('avg_aqi', sa.Float(), nullable=False),
    sa.Column('max_aqi', sa.Float(), nullable=False),
    sa.Column('min_aqi', sa.Float(), nullable=False),
    sa.Column('health_risk_score', sa.Float(), nullable=False),
    sa.Column('distance_penalty_score', sa.Float(), nullable=False),
    sa.Column('time_penalty_score', sa.Float(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('route_rank', sa.Integer(), nullable=False),
    sa.Column('recommendation_type', sa.Enum('SAFEST', 'FASTEST', 'BALANCED', name='recommendationtype'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['route_history.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_scores_composite_score'), 'route_scores', ['composite_score'], unique=False)
    op.create_index(op.f('ix_route_scores_id'), 'route_scores', ['id'], unique=False)
    op.create_index(op.f('ix_route_scores_route_id'), 'route_scores', ['route_id'], unique=False)
    op.create_index(op.f('ix_route_scores_route_rank'), 'route_scores', ['route_rank'], unique=False)
    op.create_table('route_waypoints',
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['prediction_history.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['route_history.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_waypoints_id'), 'route_waypoints', ['id'], unique=False)
    op.create_index(op.f('ix_route_waypoints_prediction_id'), 'route_waypoints', ['prediction_id'], unique=False)
    op.create_index(op.f('ix_route_waypoints_route_id'), 'route_waypoints', ['route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_waypoints_route_id'), table_name='route_waypoints')
    op.drop_index(op.f('ix_route_waypoints_prediction_id'), table_name='route_waypoints')
    op.drop_index(op.f('ix_route_waypoints_id'), table_name='route_waypoints')
    op.drop_table('route_waypoints')
    op.drop_index(op.f('ix_route_scores_route_rank'), table_name='route_scores')
    op.drop_index(op.f('ix_route_scores_route_id'), table_name='route_scores')
    op.drop_index(op.f('ix_route_scores_id'), table_name='route_scores')
    op.drop_index(op.f('ix_route_scores_composite_score'), table_name='route_scores')
    op.drop_table('route_scores')
    op.drop_index(op.f('ix_health_advisory_logs_user_id'), table_name='health_advisory_logs')
    op.drop_index(op.f('ix_health_advisory_logs_route_id'), table_name='health_advisory_logs')
    op.drop_index(op.f('ix_health_advisory_logs_prediction_id'), table_name='health_advisory_logs')
    op.drop_index(op.f('ix_health_advisory_logs_id'), table_name='health_advisory_logs')
    op.drop_table('health_advisory_logs')
    op.drop_index(op.f('ix_route_history_user_id'), table_name='route_history')
    op.drop_index(op.f('ix_route_history_id'), table_name='route_history')
    op.drop_table('route_history')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_health_profiles_id'), table_name='health_profiles')
    op.drop_table('health_profiles')
    op.drop_index(op.f('ix_favorite_routes_user_id'), table_name='favorite_routes')
    op.drop_index(op.f('ix_favorite_routes_id'), table_name='favorite_routes')
    op.drop_table('favorite_routes')
    op.drop_index(op.f('ix_exposure_history_user_id'), table_name='exposure_history')
    op.drop_index(op.f('ix_exposure_history_id'), table_name='exposure_history')
    op.drop_table('exposure_history')
    op.drop_index(op.f('ix_city_aqi_snapshots_id'), table_name='city_aqi_snapshots')
    op.drop_index(op.f('ix_city_aqi_snapshots_city_id'), table_name='city_aqi_snapshots')
    op.drop_table('city_aqi_snapshots')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_prediction_history_prediction_timestamp'), table_name='prediction_history')
    op.drop_index(op.f('ix_prediction_history_longitude'), table_name='prediction_history')
    op.drop_index(op.f('ix_prediction_history_latitude'), table_name='prediction_history')
    op.drop_index(op.f('ix_prediction_history_id'), table_name='prediction_history')
    op.drop_table('prediction_history')
    op.drop_index(op.f('ix_city_master_name'), table_name='city_master')
    op.drop_index(op.f('ix_city_master_id'), table_name='city_master')
    op.drop_table('city_master')
    op.drop_index(op.f('ix_api_logs_status'), table_name='api_logs')
    op.drop_index(op.f('ix_api_logs_id'), table_name='api_logs')
    op.drop_index(op.f('ix_api_logs_endpoint'), table_name='api_logs')
    op.drop_table('api_logs')
    # ### end Alembic commands ###
